fix: preprocessing breakend records fails (#322)
### Description

varlociraptor fails when preprocessing a pair of breakend entries
returning the following error:
```
thread 'test79_exact_mode' panicked at 'called `Option::unwrap()` on a `None` value', src/calling/variants/preprocessing/mod.rs:600:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### QC
<!-- Make sure that you can tick the boxes below. -->

* [x] The PR contains a test case for the changes or the changes are
already covered by an existing test case.
* [ ] The documentation at
https://github.com/varlociraptor/varlociraptor.github.io is updated in a
separate PR to reflect the changes or this is not necessary (e.g. if the
change does neither modify the calling grammar nor the behavior or
functionalities of Varlociraptor).

Co-authored-by: Johannes Koester <johannes.koester@uk-essen.de>